#!/usr/bin/env node
/**
 * Revarity Creative Engine — orchestrator
 * ----------------------------------------
 * Implements the pipeline described in .claude/skills/creative-engine/SKILL.md:
 *   1. Strategy  (architect)   → validate configs, build the run manifest.
 *   2. Generate  (implementer) → copy-gen (template 1) + image-prompt-gen (template 2).
 *   3. QA        (reviewer)     → deterministic copy/prompt gate (template 3, text layer).
 *   4. Output    → write the human review queue + run-<ts>.md summary. STOP (human gate).
 *
 * Guardrails enforced in code (DECISIONS.md):
 *   - D-01: pricing guard. Flagged variants may not hardcode a fee/price; projected
 *           income must carry a range + "estimate"/"typical". [PENDING-D01] token only.
 *   - D-03: image prompts must NOT request fabricated people-as-testimonials.
 *   - D-04: this engine NEVER publishes. It stops at output/. Render + upload are downstream.
 *   - Brand kit is law: palette ink/cream/gold, fonts Fraunces/Manrope/JetBrains Mono,
 *           no emoji, no off-brand color.
 *
 * COPY is generated by a real model call (copy_generation model in model-routing.json,
 * honoring template 1 + the D-01 pricing guard); FALLBACK_COPY is used only if the call
 * fails. IMAGE PROMPTS follow template 2. The IMAGE RENDER (render.mjs) and screenshot QA
 * (qa.mjs) run downstream; each creative carries render_status "PENDING_RENDER" until then.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(__dirname, "output");

// ── RUN PARAMETERS (env-overridable for volume/campaign runs) ───────────────────
//   ANGLES=all|AD1_DEAL_LIST,AD3_INCOME_ESTIMATE  VARIANTS=4  FORMATS=meta_feed_square,...  MODE=cold
//   e.g. "army of content": ANGLES=all VARIANTS=5 node creative-engine/pipeline.mjs --clean
const ALL_ANGLE_IDS = JSON.parse(fs.readFileSync(path.join(ROOT, "creative-engine/ad-angles.json"), "utf8")).angles.map((a) => a.id);
const RUN = {
  angle_ids: !process.env.ANGLES || process.env.ANGLES === "all"
    ? (process.env.ANGLES === "all" ? ALL_ANGLE_IDS : ["AD3_INCOME_ESTIMATE", "AD1_DEAL_LIST"])
    : process.env.ANGLES.split(",").map((s) => s.trim()).filter(Boolean),
  variants_per_angle: Number(process.env.VARIANTS) || 3,
  formats: (process.env.FORMATS ? process.env.FORMATS.split(",").map((s) => s.trim()) : ["meta_feed_square", "meta_story_vertical"]).filter(Boolean),
  mode: process.env.MODE || "cold",
};

// ── load + validate configs (Strategy / architect, SKILL step 1) ───────────────
const readJson = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), "utf8"));
const brand = readJson("brand-kit/brand.json");
const angles = readJson("creative-engine/ad-angles.json");
const routing = readJson("creative-engine/model-routing.json");

// ── env + copy-gen model resolution (claude-* → Anthropic, gemini-* → Gemini) ────
(function loadEnv() {
  const p = path.join(ROOT, ".env.local");
  if (!fs.existsSync(p)) return;
  for (const line of fs.readFileSync(p, "utf8").split(/\r?\n/)) {
    if (line.trim().startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const k = line.slice(0, eq).trim();
    if (!/^[A-Z0-9_]+$/.test(k) || process.env[k]) continue;
    process.env[k] = line.slice(eq + 1).trim().replace(/^["']|["']$/g, ""); // split on first =, strip quotes
  }
})();
const COPY_MODEL = (() => {
  const want = routing.tasks.copy_generation.model;
  if (want.startsWith("claude") && !process.env.ANTHROPIC_API_KEY) return { model: "gemini-2.5-flash", provider: "gemini", fellBack: want };
  return { model: want, provider: want.startsWith("claude") ? "anthropic" : "gemini", fellBack: null };
})();
// Proven patterns mined by swipe.mjs (optional). Copy-gen draws on these if present.
const SWIPE = (() => {
  try { const p = path.join(ROOT, "creative-engine/swipe-patterns.json"); return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, "utf8")).patterns : null; } catch { return null; }
})();

function validateConfigs() {
  const problems = [];
  for (const k of ["ink", "cream", "gold"]) if (!brand.palette?.[k]) problems.push(`brand.palette.${k} missing`);
  for (const k of ["display", "ui", "mono"]) if (!brand.typography?.[k]) problems.push(`brand.typography.${k} missing`);
  for (const id of RUN.angle_ids) if (!angles.angles.find((a) => a.id === id)) problems.push(`angle ${id} not in ad-angles.json`);
  for (const f of RUN.formats) {
    const s = brand.creative_specs?.[f];
    if (!s) problems.push(`format ${f} not in brand.creative_specs`);
    else if (!(Number(s.w) > 0 && Number(s.h) > 0)) problems.push(`format ${f} missing numeric w/h`);
  }
  for (const t of ["copy_generation", "image_prompt_generation", "image_render", "qa_review"]) if (!routing.tasks?.[t]) problems.push(`routing task ${t} missing`);
  return problems;
}

// ── FALLBACK COPY — used only if the live copy_generation model call fails ──────
// Hand-authored, brand-voice-correct, pricing-guard-honoring. Keeps the pipeline
// resilient (and seeds AD1/AD3 if the model is unavailable).
const FALLBACK_COPY = {
  AD3_INCOME_ESTIMATE: [
    {
      id: "A",
      headline: "How much could your area make on Airbnb?",
      body: "Pick your market and bedroom count. You get a conservative-to-optimistic monthly revenue range — an estimate from real market data, not a hype number. You fund it, you sign the lease, we run it.",
      cta: "Get my free income estimate",
    },
    {
      id: "B",
      headline: "Most owners underestimate their market by hundreds a month.",
      body: "The gap between a guess and the actual market estimate is usually wider than people expect. See a ranged, market-level estimate for your city in under a minute. The property-specific number comes from a real analysis on your call.",
      cta: "Show me the numbers",
    },
    {
      id: "C",
      headline: "A straight revenue range before you spend a dollar.",
      body: "No webinar, no hard sell. Choose your market and bedrooms, get an honest revenue range built on current market data. If the numbers make sense, we run the unit for you. If they don't, you'll know that too.",
      cta: "See my estimate",
    },
  ],
  AD1_DEAL_LIST: [
    {
      id: "A",
      headline: "We just found Airbnb lease deals in your city.",
      body: "A short list of arbitrage-ready units worth a look this month — rent, a projected revenue range, and the honest risks on each. You sign the lease, we run it. See what's actually moving in your market.",
      cta: "See the deals",
    },
    {
      // approved angle carries pricing_flag PENDING-D01 → fee stays agnostic; income ranged.
      id: "B",
      headline: "$1,800–$2,400/month. One unit. No daily involvement.",
      body: "A typical monthly revenue estimate for one managed arbitrage unit — a range, not a promise. You fund and sign; we handle guests, cleaning, and pricing. Flat monthly fee, no revenue share. [PENDING-D01]",
      cta: "Get the deal list",
      pricing_flag: "PENDING-D01",
    },
    {
      id: "C",
      headline: "Some of these deals don't last the month.",
      body: "Good arbitrage units get taken. We keep a running list for each city — rent, a projected revenue range, and the real risks on every one. No countdown gimmicks, just what's available right now.",
      cta: "Send me the deals",
    },
  ],
};

// ── IMAGE-PROMPT GENERATION (Generate / implementer — prompts.md template 2) ────
// Translate each angle's theme into a PHOTOGRAPHIC scene (not literal icons/charts).
// visual_direction in ad-angles.json reads literally ("calculator", "skyline", "deal-card")
// which pushes the model toward flat clipart — so we reinterpret it as editorial photography.
const PHOTO_SCENE = {
  AD3_INCOME_ESTIMATE:
    "A sunlit, beautifully furnished modern short-term-rental living space, shot like an editorial interiors spread. Warm natural window light, considered styling, fine tactile materials (oak, linen, brass, stone), a few quiet design objects, shallow depth of field. Calm, aspirational, the feel of a premium property portfolio.",
  AD1_DEAL_LIST:
    "An editorial still life: a premium printed property portfolio / leather-bound lookbook resting on a warm walnut desk, beside a brass desk lamp and a cup of coffee, soft directional window light, a city skyline softly out of focus in the far background. The feel of a serious private-investment brief — quality paper and materials, not an infographic.",
  AD2_CLEANING_QUOTE:
    "A pristine, freshly turned-over short-term-rental bedroom or ensuite — crisp folded white linens, neatly restocked amenities, fresh towels, soft morning light, shallow depth of field, editorial hotel-grade detail. Operational competence and calm. No people.",
  AD4_STARTER_GUIDE:
    "An editorial flat-lay of a premium printed guide/booklet on a warm neutral linen surface — quality matte blank cover (no text), a brass pen, a coffee cup, a sprig of greenery, soft daylight from one side. The feel of a serious, well-made field manual. No readable text. No people.",
  AD5_DIRECT_OFFER:
    "A premium architectural still life at golden hour — the interior of a beautifully furnished modern urban rental, or its exterior facade, confident and high-end, warm filmic grade, generous negative space. Founder-grade credibility expressed through quality of space and light, NOT through any depicted person. No people.",
};

function buildImagePrompt(angle, variant, spec) {
  const p = brand.palette;
  const orientation = spec.h > spec.w ? "vertical 9:16 story" : spec.w === spec.h ? "square 1:1 feed" : "landscape";
  const headlineZone = spec.h > spec.w ? "lower third" : "upper-left quadrant";
  return [
    `High-end EDITORIAL PHOTOGRAPH used as an ad background for Revarity (done-for-you short-term-rental operator). ${orientation} composition, ${spec.w}x${spec.h}px.`,
    ``,
    `AESTHETIC (critical): photoreal, magazine-quality editorial photography — the register of Architectural Digest, Kinfolk, Cereal, or a financial broadsheet's weekend supplement. Cinematic, tactile, soft natural light, shallow depth of field, real materials.`,
    `HARD BAN on look — these read cheap/dated and must NOT appear: flat vector illustration, clipart, infographics, icon graphics, bar/line charts, calculator or skyline icons, isometric art, cartoon, 2000s/2010s flat design, generic SaaS/startup illustration, gradient mesh, stock-photo gloss.`,
    ``,
    `ABSOLUTE RULE — NO TEXT, NO NUMBERS: render ZERO letters, words, digits, currency symbols ($), percentages, labels, captions, brand names, or logos anywhere. No documents with readable text. All copy is overlaid in post; the model must not invent any.`,
    `PROPS MUST BE UNBRANDED & LABEL-FREE (common failure): every object surface is blank — plain book covers and spines with no titles, unlabeled candles/jars/bottles, unmarked folders and packaging, no signage, no printed matter, no engravings. If a prop would normally carry text or a brand, render it blank. NEVER a real hotel/brand name (e.g. no "Peninsula", "Marriott", etc.).`,
    ``,
    `COLOR GRADE toward the brand: warm filmic neutrals — cream/bone (${p.cream}) light and deep ink (${p.ink}) shadow, with gold/brass (${p.gold}) appearing naturally in the materials and light as a sparing accent. Muted, editorial, expensive. NO purple, NO SaaS-blue, NO neon.`,
    `COMPOSITION: generous negative space. Keep the ${headlineZone} completely EMPTY — no props, no clutter, just an unbroken wall, soft surface, rug, or out-of-focus area — reserved for a headline overlay. Push all furniture/objects to the opposite side of the frame so that zone stays clean.`,
    ``,
    `SUBJECT: ${PHOTO_SCENE[angle.id] || angle.visual_direction}`,
    ``,
    `BANNED (hard): no fabricated human faces or people presented as clients/founders/testimonials; no AI talking-head; no emoji; no third-party logos (Airbnb/Meta/etc.); and per the rule above, NO rendered text or numbers whatsoever.`,
    `(A headline will be overlaid later in the ${headlineZone}; do NOT draw it or any placeholder text.)`,
  ].join("\n");
}

// ── QA PASS (reviewer — prompts.md template 3, text/prompt layer) ───────────────
const BANNED_HYPE = ["revolutionary", "insane", "game-changing", "game changing", "unbelievable", "secret"];
const EMOJI = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{2190}-\u{21FF}\u{2B00}-\u{2BFF}]/u; // arrows like → excluded below
const ARROW_OK = /[→←]/g; // → is allowed as a CTA glyph, not an emoji

function qaCreative(angle, variant, spec, imagePrompt) {
  const reasons = [];
  const copyText = `${variant.headline} ${variant.body} ${variant.cta}`;
  const lc = copyText.toLowerCase();

  // 1. hype words
  for (const w of BANNED_HYPE) if (lc.includes(w)) reasons.push(`banned hype word: "${w}"`);

  // 2. emoji (arrows allowed)
  if (EMOJI.test(copyText.replace(ARROW_OK, ""))) reasons.push("emoji present in copy");

  // 3. pricing guard (D-01) — applies to EVERY variant, flagged or not
  const feeWordNearMoney = /(?:fee|setup|deposit|price|cost|pricing|retainer)\b[^.]{0,16}\$\s?\d|\$\s?\d[\d,]*\s?[kK]?[^.]{0,12}(?:fee|setup|deposit|retainer)/i;
  if (feeWordNearMoney.test(copyText) && !copyText.includes("[PENDING-D01]"))
    reasons.push("states a fee/price near a $ figure without the [PENDING-D01] token (D-01 violation)");
  if (/\$\s?375\b|\$\s?(?:12|35)\s?[kK]\b|\$\s?(?:12|35)[,.]?\d{3}\b/i.test(copyText))
    reasons.push("hardcoded the locked $375 / $12K / $35K pricing figures (D-01 violation)");

  // 4. projected income must be a range AND labeled estimate/typical (brand voice)
  const moneyMonth = copyText.match(/\$\s?\d[\d,]*(?:\s*[–-]\s*\$?\d[\d,]*)?\s*\/?\s*(?:mo\b|month)/i);
  if (moneyMonth) {
    const hasRange = /[–-]/.test(moneyMonth[0]);
    const hasEstimateWord = /\b(estimate|typical|range)\b/i.test(copyText);
    if (!(hasRange && hasEstimateWord)) reasons.push("projected income must be a RANGE and labeled 'estimate'/'typical' (brand voice / D-01)");
  }

  // 5. image-prompt brand checks
  const ipl = imagePrompt.toLowerCase();
  if (/(purple|saas-blue|neon)/.test(ipl) && !/no purple|no saas-blue|no neon/.test(ipl)) reasons.push("image prompt requests off-brand color");
  if (!/(testimonial|talking-head|fabricated)/.test(ipl)) reasons.push("image prompt missing explicit no-fabricated-person guard (D-03)");
  if (!/(ink|cream|gold)/.test(ipl)) reasons.push("image prompt does not reference the brand palette");

  // 6. spec dimensions present
  if (!spec.w || !spec.h) reasons.push("spec missing dimensions");

  // image-level checks (garbled text, rendered color, headline legibility) require the
  // rendered PNG → cannot run until image_render produces an asset.
  const textVerdict = reasons.length === 0 ? "pass" : "fail";
  return {
    text_layer_verdict: textVerdict,
    reasons,
    image_layer_verdict: "PENDING_RENDER",
    image_layer_note: "image-layer QA (garbled text / color / headline legibility) runs in qa.mjs after render.",
    qa_model: routing.tasks.qa_review.model,
  };
}

// ── COPY GENERATION (Generate / implementer — prompts.md template 1, real model call) ──
function copyGenPrompt(angle, n) {
  const baselines = (angle.variants || []).map((v) => `"${v.headline}"`).join("; ") || "(none)";
  return [
    "You are generating Facebook/Instagram ad copy for Revarity, a done-for-you short-term-rental (Airbnb arbitrage) operator selling to people with real capital.",
    "",
    "Brand voice (hard rules):",
    "- Direct, short sentences. NO hype adjectives (banned: revolutionary, insane, game-changing, unbelievable, secret).",
    '- State the model honestly ("you fund it, you sign the lease, we run it"). Never hide the trade.',
    '- Any projected number MUST carry a range AND the word "estimate" or "typical" — never a bare promise, never a single hero number.',
    "- No fake scarcity beyond what is true (no invented countdowns). No emoji.",
    "",
    'Pricing guard (decision D-01 unresolved): do NOT state any specific price, fee, or setup cost. Write pricing-agnostic (e.g. "flat monthly fee, no revenue share") and put the literal token [PENDING-D01] where a number would otherwise go.',
    "",
    `Angle: ${angle.id} — audience: ${angle.audience || ""}`,
    `Lead magnet: ${angle.lead_magnet || ""}`,
    `Approved baseline headlines to vary AROUND (write fresh variations in the same spirit; do not copy verbatim): ${baselines}`,
    SWIPE ? `Proven patterns to DRAW ON (adapt to this angle; never copy wording): hooks=${JSON.stringify(SWIPE.hooks || [])}; angles=${JSON.stringify((SWIPE.angles || []).slice(0, 6))}; frameworks=${JSON.stringify(SWIPE.copy_frameworks || [])}` : "",
    `Generate exactly ${n} DISTINCT variants, each a different hook. Body = 1-2 short sentences.`,
    "",
    'Return ONLY a JSON array: [{"headline":"","body":"","cta":""}, ...]',
  ].join("\n");
}

async function callModelText(resolved, prompt) {
  if (resolved.provider === "anthropic") {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "x-api-key": process.env.ANTHROPIC_API_KEY, "anthropic-version": "2023-06-01", "content-type": "application/json" },
      body: JSON.stringify({ model: resolved.model, max_tokens: 1500, messages: [{ role: "user", content: prompt + "\n\nReturn ONLY the JSON array." }, { role: "assistant", content: "[" }] }),
    });
    if (!res.ok) throw new Error(`Anthropic ${resolved.model} ${res.status}: ${(await res.text()).slice(0, 160)}`);
    const data = await res.json();
    return "[" + (data?.content?.map((b) => b.text || "").join("") || "");
  }
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${resolved.model}:generateContent`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-goog-api-key": process.env.GEMINI_API_KEY },
    body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }], generationConfig: { responseMimeType: "application/json", temperature: 0.8 } }),
  });
  if (!res.ok) throw new Error(`Gemini ${resolved.model} ${res.status}: ${(await res.text()).slice(0, 160)}`);
  const data = await res.json();
  return data?.candidates?.[0]?.content?.parts?.map((p) => p.text).join("") || "[]";
}

async function generateCopy(angle, n) {
  if (!process.env.GEMINI_API_KEY && !process.env.ANTHROPIC_API_KEY) return null;
  try {
    const txt = await callModelText(COPY_MODEL, copyGenPrompt(angle, n));
    let arr;
    try { arr = JSON.parse(txt); } catch { const m = txt.match(/\[[\s\S]*\]/); arr = m ? JSON.parse(m[0]) : null; }
    if (!Array.isArray(arr) || arr.length < n) return null;
    return arr.slice(0, n).map((v, i) => {
      const variant = { id: String.fromCharCode(65 + i), headline: String(v.headline || "").trim(), body: String(v.body || "").trim(), cta: String(v.cta || "").trim() };
      if (`${variant.headline} ${variant.body} ${variant.cta}`.includes("[PENDING-D01]")) variant.pricing_flag = "PENDING-D01";
      return variant;
    });
  } catch (e) {
    console.warn(`  copy-gen failed for ${angle.id} (${e.message}) — using fallback copy.`);
    return null;
  }
}

// ── ORCHESTRATE ─────────────────────────────────────────────────────────────────
function ts() {
  const d = new Date();
  const p = (n) => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}${p(d.getUTCMonth() + 1)}${p(d.getUTCDate())}-${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}`;
}

async function run() {
  const problems = validateConfigs();
  console.log("=== Creative Engine run ===");
  console.log("mode:", RUN.mode, "| angles:", RUN.angle_ids.join(", "), "| variants:", RUN.variants_per_angle, "| formats:", RUN.formats.join(", "));
  if (problems.length) {
    console.error("CONFIG VALIDATION FAILED:");
    problems.forEach((p) => console.error("  - " + p));
    process.exit(1);
  }
  console.log("config validation: OK (brand, ad-angles, model-routing all load + valid)");
  console.log(`copy-gen model: ${COPY_MODEL.model}${COPY_MODEL.fellBack ? ` (fallback for ${COPY_MODEL.fellBack})` : ""}\n`);

  const stamp = ts();
  const rows = [];
  let pass = 0, fail = 0;
  const skipped = [];

  for (const angleId of RUN.angle_ids) {
    const angle = angles.angles.find((a) => a.id === angleId);
    const generated = await generateCopy(angle, RUN.variants_per_angle);
    const variants = generated || (FALLBACK_COPY[angleId] || []).slice(0, RUN.variants_per_angle);
    console.log(generated ? `  ${angleId}: generated ${variants.length} variants via ${COPY_MODEL.model}` : `  ${angleId}: using fallback copy`);
    if (!variants.length) { console.error(`  ${angleId}: NO COPY (model failed, no fallback) — angle dropped`); skipped.push(angleId); continue; }
    const angleDir = path.join(OUT, angleId);
    fs.mkdirSync(angleDir, { recursive: true });

    for (const variant of variants) {
      for (const fmt of RUN.formats) {
        const spec = { name: fmt, ...brand.creative_specs[fmt] };
        const imagePrompt = buildImagePrompt(angle, variant, spec);
        const qa = qaCreative(angle, variant, spec, imagePrompt);

        const base = `${variant.id}-${fmt}`;
        const record = {
          angle_id: angleId,
          variant: variant.id,
          spec: fmt,
          dimensions: `${spec.w}x${spec.h}`,
          headline: variant.headline,
          body: variant.body,
          cta: variant.cta,
          pricing_flag: variant.pricing_flag || null,
          render_status: "PENDING_RENDER",
          render_route: {
            task: "image_render",
            engine: routing.tasks.image_render.engine,
            draft_model: routing.tasks.image_render.model,
            final_model: routing.tasks.image_render.final_render_model,
            prompt_file: `${base}.prompt.txt`,
          },
          qa,
        };

        const dest = qa.text_layer_verdict === "pass" ? angleDir : path.join(OUT, "_parked");
        fs.mkdirSync(dest, { recursive: true });
        fs.writeFileSync(path.join(dest, `${base}.json`), JSON.stringify(record, null, 2));
        fs.writeFileSync(path.join(dest, `${base}.prompt.txt`), imagePrompt + "\n");

        if (qa.text_layer_verdict === "pass") pass++; else fail++;
        rows.push({ angleId, v: variant.id, fmt, dims: record.dimensions, headline: variant.headline, verdict: qa.text_layer_verdict, reasons: qa.reasons });
      }
    }
  }

  // run summary (the human-gate table)
  const lines = [];
  lines.push(`# Creative Engine run — ${stamp}`);
  lines.push("");
  lines.push(`- **Mode:** ${RUN.mode}`);
  lines.push(`- **Angles:** ${RUN.angle_ids.join(", ")}`);
  lines.push(`- **Variants/angle:** ${RUN.variants_per_angle} · **Formats:** ${RUN.formats.join(", ")}`);
  lines.push(`- **Creatives generated:** ${pass + fail}  (text-QA pass: ${pass}, parked: ${fail})`);
  lines.push(`- **Copy-gen model:** ${COPY_MODEL.model}${COPY_MODEL.fellBack ? ` (fallback for ${COPY_MODEL.fellBack})` : ""}`);
  lines.push(`- **Render status:** \`PENDING_RENDER\` — \`render.mjs\` (Nano Banana / Gemini) renders next, then \`qa.mjs\` screens. Run the whole thing via \`pipeline.mjs\`.`);
  lines.push("");
  lines.push("> **HUMAN GATE.** Nothing here is published. After image render + screenshot QA, David/Malcolm approve before any upload. The engine does not cross this line. (D-04)");
  lines.push("");
  lines.push("| Angle | Var | Format | Dims | Text-QA | Headline | QA notes |");
  lines.push("|---|---|---|---|---|---|---|");
  for (const r of rows) {
    lines.push(`| ${r.angleId} | ${r.v} | ${r.fmt} | ${r.dims} | ${r.verdict} | ${r.headline.replace(/\|/g, "\\|")} | ${(r.reasons.join("; ") || "—").replace(/\|/g, "\\|")} |`);
  }
  lines.push("");
  lines.push("## Pipeline (run via creative-engine/pipeline.mjs)");
  lines.push("1. `render.mjs` — render each prompt with Nano Banana (draft gemini-3.1-flash-image-preview; pro only on text-fidelity need).");
  lines.push("2. `qa.mjs` — automated screenshot QA (reviewer per model-routing; escalates on uncertain).");
  lines.push("3. `regen.mjs` — re-roll any parked failures with the QA hint (up to 2x).");
  lines.push("4. `contactsheet.mjs` → review.html, then the HUMAN approval gate. Engine never publishes. (D-04)");
  lines.push("");

  const summaryPath = path.join(OUT, `run-${stamp}.md`);
  fs.writeFileSync(summaryPath, lines.join("\n"));

  console.log(`generated ${pass + fail} creatives → ${pass} queued, ${fail} parked`);
  console.log(`run summary: creative-engine/output/run-${stamp}.md`);
  console.log("STOP: human gate. Engine does not publish. (D-04)");
  if (skipped.length) {
    console.error(`\nERROR: ${skipped.length} angle(s) produced no copy and were dropped: ${skipped.join(", ")}. ` +
      `Set ANTHROPIC_API_KEY/GEMINI_API_KEY or add FALLBACK_COPY for them. Failing so an unattended run can't silently lose angles.`);
    process.exitCode = 1;
  }
}

run().catch((e) => { console.error("run failed:", e); process.exit(1); });
